"use strict";
exports.__esModule = true;
var curso_1 = require("./curso");
var capacitacion_1 = require("./capacitacion");
var Instructor_1 = require("./Instructor");
var ReadlineSync = require("readline-sync");
var input = ReadlineSync;
console.log("CREAR INSTRUCTOR");
var instructor1 = new Instructor_1.Instructor(input.question("Ingrese DNI instructor: "), input.question("Ingrese Nombre Instructor: "), input.question("Ingrese Apellido Instructor: "), input.question("Ingrese Cupo Modalidad Virtual: "));
console.log("SE AGREGO EL SIGUIENTE INSTRUCTOR:" + instructor1);
console.log("CREAR CURSO");
var curso1 = new curso_1.Curso(input.question("Ingrese Nombre del Curso: "), input.question("Ingrese Modalidad: "), input.question("Ingrese Nota Minima Curso: "));
console.log("curso creado" + curso1.getModalidad());
console.log("CREA CAPACITACION");
var capacitacion1 = new capacitacion_1.Capacitacion(curso1);
console.log("CREA CAPACITACION");
console.log("ASOCIAR INSTRUCTOR");
instructor1.inscribirACurso(capacitacion1);
console.log("LISTADO DE CURSOS" + instructor1);
